name: Generate HTML Table and Publish to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "33 */12 * * *"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-html-table:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup crane
      uses: imjasonh/setup-crane@v0.1

    - name: Setup jq
      uses: dcarbone/install-jq-action@v3

    - name: Setup helm
      uses: azure/setup-helm@v4.2.0

    - name: Run HTML table generation script
      run: ./generate-html-table.sh

    - name: Create the proper folder to be published
      run: |
        mkdir public/
        mv output.html public/index.html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
